apiVersion: apps/v1
kind: Deployment
metadata:
  name: protfolio
  labels:
    app: mine
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mine
  template:
    metadata:
      labels:
        app: mine
    spec:
      containers:
      - name: cont1
        image: gopalarao2004/gopal-portfolio:tagname

---
apiVersion: v1
kind: Service
metadata:
  name: protfolioservice
spec:
  type: LoadBalancer
  selector:
    app: mine
  ports:
    - port: 80
      nodeport: 31433
